-- TimeSpace Script generated by friends111's python script. Replace all %TODO% values accordingly, check for errors (packet-generation isn't perfect), and modify things if needed.
local Map = require('Map')
local Monster = require('Monster')
local Event = require('Event')
local MapObject = require('MapObject')
local MapNpc = require('MapNpc')
local Portal = require('Portal')
local Location = require('Location')
local TimeSpace = require('TimeSpace')
local PortalType = require("PortalType")
local PortalMinimapOrientation = require('PortalMinimapOrientation')
local TimeSpaceObjective = require('TimeSpaceObjective')
local TimeSpaceTaskType = require('TimeSpaceTaskType')
local TimeSpaceTask = require('TimeSpaceTask')

local objectives = TimeSpaceObjective.Create()
    .WithGoToExit()
    .WithInteractObjects(1048, 4)

-- Grid min:(2, 7) ~ max:(5, 11) (width: 3, height: 4)
--     [ 0][ 1][ 2][ 3][ 4][ 5][ 6][ 7][ 8][ 9][10]
-- [ 0][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ]
-- [ 1][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ]
-- [ 2][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ]
-- [ 3][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ]
-- [ 4][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ]
-- [ 5][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ]
-- [ 6][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ]
-- [ 7][  ][  ][XX][XX][XX][  ][  ][  ][  ][  ][  ]
-- [ 8][  ][  ][OO][OO][OO][OO][  ][  ][  ][  ][  ]
-- [ 9][  ][  ][OO][OO][OO][XX][  ][  ][  ][  ][  ]
-- [10][  ][  ][  ][OO][XX][  ][  ][  ][  ][  ][  ]
-- [11][  ][  ][  ][OO][  ][  ][  ][  ][  ][  ][  ]

local map_3_11 = Map.Create().WithMapId(4201).SetMapCoordinates(3, 11).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None)
) -- start
local map_3_10 = Map.Create().WithMapId(4212).SetMapCoordinates(3, 10).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None).WithOnStartDialog(6104)
)
local map_3_9 = Map.Create().WithMapId(4200).SetMapCoordinates(3, 9).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None).WithOnStartShout("TS_20_TEXT_0")
)
local map_2_9 = Map.Create().WithMapId(4207).SetMapCoordinates(2, 9).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None)
)
local map_2_8 = Map.Create().WithMapId(4206).SetMapCoordinates(2, 8).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None).WithOnStartShout("TS_20_TEXT_1")
)
local map_2_7 = Map.Create().WithMapId(4203).SetMapCoordinates(2, 7).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.KillAllMonsters).WithOnFinishDialog(6106)
)
local map_3_8 = Map.Create().WithMapId(4206).SetMapCoordinates(3, 8).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None).WithOnStartShout("TS_20_TEXT_2")
)
local map_3_7 = Map.Create().WithMapId(4203).SetMapCoordinates(3, 7).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.KillAllMonsters).WithOnFinishDialog(6109)
)
local map_4_9 = Map.Create().WithMapId(4210).SetMapCoordinates(4, 9).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None)
)
local map_4_8 = Map.Create().WithMapId(4212).SetMapCoordinates(4, 8).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None).WithOnStartShout("TS_20_TEXT_3")
)
local map_4_7 = Map.Create().WithMapId(4203).SetMapCoordinates(4, 7).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.KillAllMonsters).WithTaskText("TS_20_TEXT_4").WithOnFinishDialog(6105)
)
local map_5_8 = Map.Create().WithMapId(4209).SetMapCoordinates(5, 8).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None)
)
local map_5_9 = Map.Create().WithMapId(4201).SetMapCoordinates(5, 9).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.KillAllMonsters).WithOnFinishDialog(6107)
)
local map_4_10 = Map.Create().WithMapId(5100).SetMapCoordinates(4, 10).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.KillAllMonsters).WithTaskText("TS_20_TEXT_4").WithOnFinishDialog(6110)
)

local portal_3_11_to_3_10 = Portal.Create(PortalType.TsNormal).From(map_3_11, 14, 1).To(map_3_10, 14, 28).MinimapOrientation(PortalMinimapOrientation.North)
local portal_3_10_to_3_9 = Portal.Create(PortalType.TsNormal).From(map_3_10, 14, 1).To(map_3_9, 14, 28).MinimapOrientation(PortalMinimapOrientation.North)
local portal_3_10_to_4_10 = Portal.Create(PortalType.Locked).From(map_3_10, 28, 15).To(map_4_10, 1, 15).MinimapOrientation(PortalMinimapOrientation.East)
local portal_3_10_to_3_11 = Portal.Create(PortalType.TsNormal).From(map_3_10, 14, 28).To(map_3_11, 14, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_3_9_to_3_8 = Portal.Create(PortalType.TsNormal).From(map_3_9, 14, 1).To(map_3_8, 14, 28).MinimapOrientation(PortalMinimapOrientation.North)
local portal_3_9_to_4_9 = Portal.Create(PortalType.TsNormal).From(map_3_9, 28, 15).To(map_4_9, 1, 15).MinimapOrientation(PortalMinimapOrientation.East)
local portal_3_9_to_3_10 = Portal.Create(PortalType.TsNormal).From(map_3_9, 14, 28).To(map_3_10, 14, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_3_9_to_2_9 = Portal.Create(PortalType.TsNormal).From(map_3_9, 1, 15).To(map_2_9, 28, 15).MinimapOrientation(PortalMinimapOrientation.West)
local portal_4_9_to_4_8 = Portal.Create(PortalType.TsNormal).From(map_4_9, 15, 1).To(map_4_8, 14, 28).MinimapOrientation(PortalMinimapOrientation.North)
local portal_4_9_to_3_9 = Portal.Create(PortalType.TsNormal).From(map_4_9, 1, 15).To(map_3_9, 28, 15).MinimapOrientation(PortalMinimapOrientation.West)
local portal_4_8_to_4_7 = Portal.Create(PortalType.TsNormal).From(map_4_8, 14, 1).To(map_4_7, 14, 28).MinimapOrientation(PortalMinimapOrientation.North)
local portal_4_8_to_5_8 = Portal.Create(PortalType.TsNormal).From(map_4_8, 28, 15).To(map_5_8, 1, 15).MinimapOrientation(PortalMinimapOrientation.East)
local portal_4_8_to_4_9 = Portal.Create(PortalType.TsNormal).From(map_4_8, 14, 28).To(map_4_9, 15, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_4_7_to_4_8 = Portal.Create(PortalType.Locked).From(map_4_7, 14, 28).To(map_4_8, 14, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_2_9_to_2_8 = Portal.Create(PortalType.TsNormal).From(map_2_9, 14, 1).To(map_2_8, 14, 28).MinimapOrientation(PortalMinimapOrientation.North)
local portal_2_9_to_3_9 = Portal.Create(PortalType.TsNormal).From(map_2_9, 28, 15).To(map_3_9, 1, 15).MinimapOrientation(PortalMinimapOrientation.East)
local portal_2_8_to_2_7 = Portal.Create(PortalType.Locked).From(map_2_8, 14, 1).To(map_2_7, 14, 28).MinimapOrientation(PortalMinimapOrientation.North)
local portal_2_8_to_2_9 = Portal.Create(PortalType.TsNormal).From(map_2_8, 14, 28).To(map_2_9, 14, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_2_7_to_2_8 = Portal.Create(PortalType.Locked).From(map_2_7, 14, 28).To(map_2_8, 14, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_3_8_to_3_7 = Portal.Create(PortalType.Locked).From(map_3_8, 14, 1).To(map_3_7, 14, 28).MinimapOrientation(PortalMinimapOrientation.North)
local portal_3_8_to_3_9 = Portal.Create(PortalType.TsNormal).From(map_3_8, 14, 28).To(map_3_9, 14, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_5_8_to_5_9 = Portal.Create(PortalType.Locked).From(map_5_8, 14, 28).To(map_5_9, 14, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_5_8_to_4_8 = Portal.Create(PortalType.TsNormal).From(map_5_8, 1, 15).To(map_4_8, 28, 15).MinimapOrientation(PortalMinimapOrientation.West)
local portal_5_9_to_5_8 = Portal.Create(PortalType.Locked).From(map_5_9, 14, 1).To(map_5_8, 14, 28).MinimapOrientation(PortalMinimapOrientation.North)
local portal_3_7_to_3_8 = Portal.Create(PortalType.Locked).From(map_3_7, 14, 28).To(map_3_8, 14, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_4_10_to_UNKNOWN = Portal.Create(PortalType.TSEndClosed).From(map_4_10, 28, 14).To(map_4_10, 28, 14).MinimapOrientation(PortalMinimapOrientation.East)
local portal_4_10_to_3_10 = Portal.Create(PortalType.Locked).From(map_4_10, 1, 15).To(map_3_10, 28, 15).MinimapOrientation(PortalMinimapOrientation.West)

map_3_11.AddPortal(portal_3_11_to_3_10)
map_3_10.AddPortal(portal_3_10_to_3_9)
map_3_10.AddPortal(portal_3_10_to_4_10)
map_3_10.AddPortal(portal_3_10_to_3_11)
map_3_9.AddPortal(portal_3_9_to_3_8)
map_3_9.AddPortal(portal_3_9_to_4_9)
map_3_9.AddPortal(portal_3_9_to_3_10)
map_3_9.AddPortal(portal_3_9_to_2_9)
map_4_9.AddPortal(portal_4_9_to_4_8)
map_4_9.AddPortal(portal_4_9_to_3_9)
map_4_8.AddPortal(portal_4_8_to_4_7)
map_4_8.AddPortal(portal_4_8_to_5_8)
map_4_8.AddPortal(portal_4_8_to_4_9)
map_4_7.AddPortal(portal_4_7_to_4_8)
map_2_9.AddPortal(portal_2_9_to_2_8)
map_2_9.AddPortal(portal_2_9_to_3_9)
map_2_8.AddPortal(portal_2_8_to_2_7)
map_2_8.AddPortal(portal_2_8_to_2_9)
map_2_7.AddPortal(portal_2_7_to_2_8)
map_3_8.AddPortal(portal_3_8_to_3_7)
map_3_8.AddPortal(portal_3_8_to_3_9)
map_5_8.AddPortal(portal_5_8_to_5_9)
map_5_8.AddPortal(portal_5_8_to_4_8)
map_5_9.AddPortal(portal_5_9_to_5_8)
map_3_7.AddPortal(portal_3_7_to_3_8)
map_4_10.AddPortal(portal_4_10_to_UNKNOWN)
map_4_10.AddPortal(portal_4_10_to_3_10)

--- Map 3_11
map_3_11.OnMapJoin({
    Event.TryStartTaskForMap(map_3_11),
})
---

--- Map 3_10
map_3_10.OnMapJoin({
    Event.TryStartTaskForMap(map_3_10),
})
---

--- Map 3_9
map_3_9.OnMapJoin({
    Event.TryStartTaskForMap(map_3_9),
})
---

--- Map 2_9
map_2_9.OnMapJoin({
    Event.TryStartTaskForMap(map_2_9),
})
---

--- Map 2_8
map_2_8.AddMonsters({
    Monster.CreateWithVnum(141).At(18, 16).Facing(7), -- Mimic [16:31:50]
    Monster.CreateWithVnum(100).At(12, 13).Facing(5), -- Poisonous Hamster [16:31:50]
    Monster.CreateWithVnum(100).At(10, 11).Facing(6), -- Poisonous Hamster [16:31:50]
    Monster.CreateWithVnum(100).At(23, 16).Facing(2).SpawnAfterMobsKilled(1), -- Poisonous Hamster [16:31:51]
    Monster.CreateWithVnum(141).At(12, 18).Facing(7).SpawnAfterMobsKilled(2), -- Mimic [16:31:53]
})
map_2_8.OnMapJoin({
    Event.TryStartTaskForMap(map_2_8),
})
---

--- Map 2_7
map_2_7.AddMonsters({
    Monster.CreateWithVnum(100).At(7, 17).Facing(0), -- Poisonous Hamster [16:32:01]
    Monster.CreateWithVnum(100).At(6, 14).Facing(5), -- Poisonous Hamster [16:32:01]
    Monster.CreateWithVnum(100).At(8, 11).Facing(4).SpawnAfterMobsKilled(2), -- Poisonous Hamster [16:32:03]
    Monster.CreateWithVnum(141).At(11, 14).Facing(2).SpawnAfterMobsKilled(2), -- Mimic [16:32:03]
    Monster.CreateWithVnum(141).At(16, 13).Facing(0).SpawnAfterMobsKilled(3), -- Mimic [16:32:05]
    Monster.CreateWithVnum(141).At(19, 17).Facing(5).SpawnAfterMobsKilled(4), -- Mimic [16:32:06]
    Monster.CreateWithVnum(100).At(22, 17).Facing(0).SpawnAfterMobsKilled(5), -- Poisonous Hamster [16:32:07]
    Monster.CreateWithVnum(100).At(20, 11).Facing(0).SpawnAfterMobsKilled(6), -- Poisonous Hamster [16:32:08]
    Monster.CreateWithVnum(100).At(23, 13).Facing(5).SpawnAfterMobsKilled(6), -- Poisonous Hamster [16:32:08]
    Monster.CreateWithVnum(65).At(11, 18).Facing(5).SpawnAfterMobsKilled(8), -- Nervous Walker [16:32:11]
})
map_2_7.AddObjects({
    MapObject.CreateCrystalBall().At(15, 17).AsObjective().OnTrigger({
        Event.OpenPortal(portal_5_8_to_5_9),
    }), -- [16:32:01]
})
map_2_7.OnMapJoin({
    Event.TryStartTaskForMap(map_2_7),
})
map_2_7.OnTaskFinish({
    Event.OpenPortal(portal_2_7_to_2_8),
    Event.AddTime(100),
})
---

--- Map 3_8
map_3_8.AddMonsters({
    Monster.CreateWithVnum(141).At(20, 16).Facing(6), -- Mimic [16:32:37]
    Monster.CreateWithVnum(141).At(19, 8).Facing(6), -- Mimic [16:32:37]
    Monster.CreateWithVnum(141).At(9, 15).Facing(6), -- Mimic [16:32:37]
    Monster.CreateWithVnum(141).At(24, 16).Facing(6).SpawnAfterMobsKilled(1), -- Mimic [16:32:38]
    Monster.CreateWithVnum(141).At(12, 20).Facing(5).SpawnAfterMobsKilled(2), -- Mimic [16:32:41]
})
map_3_8.OnMapJoin({
    Event.TryStartTaskForMap(map_3_8),
})
---

--- Map 3_7
map_3_7.AddMonsters({
    Monster.CreateWithVnum(56).At(21, 15).Facing(2), -- Strong Vampie [16:33:56]
    Monster.CreateWithVnum(56).At(15, 19).Facing(4), -- Strong Vampie [16:33:56]
    Monster.CreateWithVnum(56).At(10, 10).Facing(0), -- Strong Vampie [16:33:56]
    Monster.CreateWithVnum(56).At(9, 13).Facing(7), -- Strong Vampie [16:33:56]
    Monster.CreateWithVnum(56).At(22, 13).Facing(4).SpawnAfterMobsKilled(3), -- Strong Vampie [16:34:00]
    Monster.CreateWithVnum(56).At(4, 15).Facing(6).SpawnAfterMobsKilled(4), -- Strong Vampie [16:34:02]
    Monster.CreateWithVnum(65).At(6, 16).Facing(7).SpawnAfterMobsKilled(6), -- Nervous Walker [16:34:05]
    Monster.CreateWithVnum(56).At(9, 19).Facing(7).SpawnAfterMobsKilled(6), -- Strong Vampie [16:34:05]
    Monster.CreateWithVnum(65).At(23, 18).Facing(0).SpawnAfterMobsKilled(7), -- Nervous Walker [16:34:07]
})
map_3_7.AddObjects({
    MapObject.CreateCrystalBall().At(14, 17).AsObjective().OnTrigger({
        Event.OpenPortal(portal_3_10_to_4_10),
    }), -- [16:33:56]
    MapObject.CreateOldBox().At(17, 5), -- [16:33:56]
    MapObject.CreateOldBox().At(15, 5), -- [16:33:56]
    MapObject.CreateOldBox().At(13, 5), -- [16:33:56]
})
map_3_7.OnMapJoin({
    Event.TryStartTaskForMap(map_3_7),
})
map_3_7.OnTaskFinish({
    Event.OpenPortal(portal_3_7_to_3_8),
    Event.AddTime(100),
})
---

--- Map 4_9
map_4_9.OnMapJoin({
    Event.TryStartTaskForMap(map_4_9),
})
---

--- Map 4_8
map_4_8.OnMapJoin({
    Event.TryStartTaskForMap(map_4_8),
})
---

--- Map 4_7
map_4_7.AddMonsters({
    Monster.CreateWithVnum(100).At(22, 17).Facing(0), -- Poisonous Hamster [16:31:12]
    Monster.CreateWithVnum(100).At(22, 10).Facing(5), -- Poisonous Hamster [16:31:12]
    Monster.CreateWithVnum(100).At(9, 14).Facing(5).SpawnAfterMobsKilled(1), -- Poisonous Hamster [16:31:13]
    Monster.CreateWithVnum(141).At(7, 18).Facing(5).SpawnAfterMobsKilled(2), -- Mimic [16:31:14]
    Monster.CreateWithVnum(141).At(14, 18).Facing(2).SpawnAfterMobsKilled(4), -- Mimic [16:31:17]
    Monster.CreateWithVnum(141).At(24, 18).Facing(4).SpawnAfterMobsKilled(5), -- Mimic [16:31:18]
    Monster.CreateWithVnum(141).At(17, 18).Facing(5).SpawnAfterMobsKilled(6), -- Mimic [16:31:20]
    Monster.CreateWithVnum(65).At(16, 12).Facing(4).SpawnAfterMobsKilled(7), -- Nervous Walker [16:31:22]
})
map_4_7.AddObjects({
    MapObject.CreateCrystalBall().At(17, 15).AsObjective().OnTrigger({
        Event.OpenPortal(portal_2_8_to_2_7),
    }), -- [16:31:12]
})
map_4_7.OnMapJoin({
    Event.TryStartTaskForMap(map_4_7),
})
map_4_7.OnTaskFinish({
    Event.OpenPortal(portal_4_7_to_4_8),
    Event.AddTime(100),
})
---

--- Map 5_8
map_5_8.AddMonsters({
    Monster.CreateWithVnum(141).At(17, 9).Facing(4), -- Mimic [16:33:08]
    Monster.CreateWithVnum(141).At(14, 16).Facing(1), -- Mimic [16:33:08]
    Monster.CreateWithVnum(141).At(15, 14).Facing(4), -- Mimic [16:33:08]
})
map_5_8.OnMapJoin({
    Event.TryStartTaskForMap(map_5_8),
})
---

--- Map 5_9
map_5_9.AddMonsters({
    Monster.CreateWithVnum(58).At(23, 11).Facing(2), -- Fire Vampie [16:33:15]
    Monster.CreateWithVnum(58).At(18, 20).Facing(0), -- Fire Vampie [16:33:15]
    Monster.CreateWithVnum(58).At(15, 19).Facing(1), -- Fire Vampie [16:33:15]
    Monster.CreateWithVnum(58).At(14, 11).Facing(0), -- Fire Vampie [16:33:15]
    Monster.CreateWithVnum(58).At(11, 19).Facing(0), -- Fire Vampie [16:33:15]
    Monster.CreateWithVnum(58).At(9, 11).Facing(4), -- Fire Vampie [16:33:15]
    Monster.CreateWithVnum(65).At(7, 15).Facing(1).SpawnAfterMobsKilled(5), -- Nervous Walker [16:33:23]
    Monster.CreateWithVnum(65).At(12, 16).Facing(3).SpawnAfterMobsKilled(5), -- Nervous Walker [16:33:23]
})
map_5_9.AddObjects({
    MapObject.CreateCrystalBall().At(16, 15).AsObjective().OnTrigger({
        Event.OpenPortal(portal_3_8_to_3_7),
    }), -- [16:33:15]
})
map_5_9.OnMapJoin({
    Event.TryStartTaskForMap(map_5_9),
})
map_5_9.OnTaskFinish({
    Event.OpenPortal(portal_5_9_to_5_8),
    Event.AddTime(100),
})
---

--- Map 4_10
map_4_10.AddMonsters({
    Monster.CreateWithVnum(58).At(23, 16).Facing(0), -- Fire Vampie [16:34:32]
    Monster.CreateWithVnum(58).At(22, 11).Facing(5), -- Fire Vampie [16:34:32]
    Monster.CreateWithVnum(58).At(21, 20).Facing(1), -- Fire Vampie [16:34:32]
    Monster.CreateWithVnum(58).At(19, 9).Facing(7), -- Fire Vampie [16:34:32]
    Monster.CreateWithVnum(58).At(16, 22).Facing(4), -- Fire Vampie [16:34:32]
    Monster.CreateWithVnum(58).At(13, 22).Facing(1), -- Fire Vampie [16:34:32]
    Monster.CreateWithVnum(58).At(13, 9).Facing(1), -- Fire Vampie [16:34:32]
    Monster.CreateWithVnum(141).At(8, 13).Facing(7).SpawnAfterMobsKilled(7), -- Mimic [16:34:50]
    Monster.CreateWithVnum(141).At(10, 7).Facing(5).SpawnAfterMobsKilled(7), -- Mimic [16:34:50]
    Monster.CreateWithVnum(141).At(10, 20).Facing(0).SpawnAfterMobsKilled(7), -- Mimic [16:34:50]
    Monster.CreateWithVnum(59).At(17, 14).Facing(4).SpawnAfterMobsKilled(8), -- Strong Fire Vampie [16:34:54]
})
map_4_10.AddNpcs({
    MapNpc.CreateNpcWithVnum(320).At(18, 17).Facing(7).WithCustomLevel(30), -- Soldier of the NosVille Guards [16:34:32]
    MapNpc.CreateNpcWithVnum(320).At(18, 11).Facing(7).WithCustomLevel(30), -- Soldier of the NosVille Guards [16:34:32]
    MapNpc.CreateNpcWithVnum(320).At(14, 18).Facing(0).WithCustomLevel(30), -- Soldier of the NosVille Guards [16:34:32]
    MapNpc.CreateNpcWithVnum(320).At(11, 16).Facing(5).WithCustomLevel(30), -- Soldier of the NosVille Guards [16:34:32]
    MapNpc.CreateNpcWithVnum(320).At(12, 12).Facing(6).WithCustomLevel(30), -- Soldier of the NosVille Guards [16:34:32]
})
map_4_10.OnMapJoin({
    Event.TryStartTaskForMap(map_4_10),
})
map_4_10.OnTaskFinish({
    Event.OpenPortal(portal_4_10_to_UNKNOWN),
})
---

local ts = TimeSpace.Create(20)  -- TimeSpace ID
    .SetMaps({map_3_11, map_3_10, map_3_9, map_2_9, map_2_8, map_2_7, map_3_8, map_3_7, map_4_9, map_4_8, map_4_7, map_5_8, map_5_9, map_4_10})
    .SetSpawn(Location.InMap(map_3_11).At(7, 9))
    .SetLives(3)
    .SetObjectives(objectives)
    .SetDurationInSeconds(150)
    .SetBonusPointItemDropChance(5000)
return ts
