-- TimeSpace Script generated by friends111's python script. Replace all %TODO% values accordingly, check for errors (packet-generation isn't perfect), and modify things if needed.
local Map = require('Map')
local Monster = require('Monster')
local Event = require('Event')
local MapObject = require('MapObject')
local Portal = require('Portal')
local Location = require('Location')
local TimeSpace = require('TimeSpace')
local PortalType = require("PortalType")
local PortalMinimapOrientation = require('PortalMinimapOrientation')
local TimeSpaceObjective = require('TimeSpaceObjective')
local TimeSpaceTaskType = require('TimeSpaceTaskType')
local TimeSpaceTask = require('TimeSpaceTask')
local MonsterWave = require('MonsterWave')

local objectives = TimeSpaceObjective.Create()
    .WithGoToExit()
    .WithInteractObjects(1182, 3)

-- Grid min:(1, 4) ~ max:(6, 8) (width: 5, height: 4)
--     [ 0][ 1][ 2][ 3][ 4][ 5][ 6][ 7][ 8][ 9][10]
-- [ 0][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ]
-- [ 1][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ]
-- [ 2][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ]
-- [ 3][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ]
-- [ 4][  ][  ][  ][OO][  ][  ][  ][  ][  ][  ][  ]
-- [ 5][  ][  ][XX][OO][XX][  ][  ][  ][  ][  ][  ]
-- [ 6][  ][XX][OO][  ][OO][OO][OO][  ][  ][  ][  ]
-- [ 7][  ][  ][OO][OO][XX][  ][  ][  ][  ][  ][  ]
-- [ 8][  ][  ][  ][OO][  ][  ][  ][  ][  ][  ][  ]
-- [ 9][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ]
-- [10][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ][  ]

local map_6_6 = Map.Create().WithMapId(4416).SetMapCoordinates(6, 6).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None)
) -- start
local map_5_6 = Map.Create().WithMapId(4409).SetMapCoordinates(5, 6).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None)
)
local map_4_6 = Map.Create().WithMapId(4402).SetMapCoordinates(4, 6).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None)
)
local map_4_5 = Map.Create().WithMapId(4405).SetMapCoordinates(4, 5).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.KillAllMonsters).WithTaskText("TS_GENERIC_TEXT_KILL_ALL_ENEMIES")
)
local map_3_5 = Map.Create().WithMapId(4403).SetMapCoordinates(3, 5).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None)
)
local map_2_5 = Map.Create().WithMapId(4408).SetMapCoordinates(2, 5).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.Survive, 140)
)
local map_4_7 = Map.Create().WithMapId(4406).SetMapCoordinates(4, 7).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.KillAllMonsters).WithTaskText("TS_GENERIC_TEXT_KILL_ALL_ENEMIES")
)
local map_3_7 = Map.Create().WithMapId(4401).SetMapCoordinates(3, 7).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None)
)
local map_2_7 = Map.Create().WithMapId(4407).SetMapCoordinates(2, 7).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None)
)
local map_2_6 = Map.Create().WithMapId(4404).SetMapCoordinates(2, 6).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None)
)
local map_1_6 = Map.Create().WithMapId(4411).SetMapCoordinates(1, 6).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.KillAllMonsters).WithTaskText("TS_GENERIC_TEXT_KILL_ALL_ENEMIES")
)
local map_3_4 = Map.Create().WithMapId(4410).SetMapCoordinates(3, 4).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None)
)
local map_3_8 = Map.Create().WithMapId(4410).SetMapCoordinates(3, 8).WithTask(
    TimeSpaceTask.Create(TimeSpaceTaskType.None)
)

local portal_6_6_to_5_6 = Portal.Create(PortalType.TsNormal).From(map_6_6, 1, 12).To(map_5_6, 23, 11).MinimapOrientation(PortalMinimapOrientation.West)
local portal_5_6_to_6_6 = Portal.Create(PortalType.TsNormal).From(map_5_6, 23, 11).To(map_6_6, 1, 12).MinimapOrientation(PortalMinimapOrientation.East)
local portal_5_6_to_4_6 = Portal.Create(PortalType.TsNormal).From(map_5_6, 1, 11).To(map_4_6, 23, 12).MinimapOrientation(PortalMinimapOrientation.West)
local portal_4_6_to_4_5 = Portal.Create(PortalType.TsNormal).From(map_4_6, 12, 1).To(map_4_5, 12, 23).MinimapOrientation(PortalMinimapOrientation.North)
local portal_4_6_to_5_6 = Portal.Create(PortalType.TsNormal).From(map_4_6, 23, 12).To(map_5_6, 1, 11).MinimapOrientation(PortalMinimapOrientation.East)
local portal_4_6_to_4_7 = Portal.Create(PortalType.TsNormal).From(map_4_6, 12, 23).To(map_4_7, 12, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_4_7_to_4_6 = Portal.Create(PortalType.Locked).From(map_4_7, 12, 1).To(map_4_6, 12, 23).MinimapOrientation(PortalMinimapOrientation.North)
local portal_4_7_to_3_7 = Portal.Create(PortalType.Locked).From(map_4_7, 1, 12).To(map_3_7, 23, 11).MinimapOrientation(PortalMinimapOrientation.West)
local portal_3_7_to_4_7 = Portal.Create(PortalType.TsNormal).From(map_3_7, 23, 11).To(map_4_7, 1, 12).MinimapOrientation(PortalMinimapOrientation.East)
local portal_3_7_to_3_8 = Portal.Create(PortalType.TsNormal).From(map_3_7, 12, 23).To(map_3_8, 12, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_3_7_to_2_7 = Portal.Create(PortalType.TsNormal).From(map_3_7, 1, 11).To(map_2_7, 23, 12).MinimapOrientation(PortalMinimapOrientation.West)
local portal_3_8_to_3_7 = Portal.Create(PortalType.TsNormal).From(map_3_8, 12, 1).To(map_3_7, 12, 23).MinimapOrientation(PortalMinimapOrientation.North)
local portal_3_8_to_UNKNOWN = Portal.Create(PortalType.TSEnd).From(map_3_8, 12, 23).To(map_3_8, 12, 23).MinimapOrientation(PortalMinimapOrientation.South)
local portal_2_7_to_2_6 = Portal.Create(PortalType.Locked).From(map_2_7, 12, 1).To(map_2_6, 12, 23).MinimapOrientation(PortalMinimapOrientation.North)
local portal_2_7_to_3_7 = Portal.Create(PortalType.Locked).From(map_2_7, 23, 12).To(map_3_7, 1, 11).MinimapOrientation(PortalMinimapOrientation.East)
local portal_2_6_to_2_5 = Portal.Create(PortalType.TsNormal).From(map_2_6, 12, 1).To(map_2_5, 12, 23).MinimapOrientation(PortalMinimapOrientation.North)
local portal_2_6_to_2_7 = Portal.Create(PortalType.TsNormal).From(map_2_6, 12, 23).To(map_2_7, 12, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_2_6_to_1_6 = Portal.Create(PortalType.TsNormal).From(map_2_6, 1, 12).To(map_1_6, 23, 11).MinimapOrientation(PortalMinimapOrientation.West)
local portal_1_6_to_2_6 = Portal.Create(PortalType.Locked).From(map_1_6, 23, 11).To(map_2_6, 1, 12).MinimapOrientation(PortalMinimapOrientation.East)
local portal_1_6_to_UNKNOWN = Portal.Create(PortalType.TSEnd).From(map_1_6, 1, 11).To(map_1_6, 1, 11).MinimapOrientation(PortalMinimapOrientation.West)
local portal_2_5_to_3_5 = Portal.Create(PortalType.Locked).From(map_2_5, 23, 12).To(map_3_5, 1, 12).MinimapOrientation(PortalMinimapOrientation.East)
local portal_2_5_to_2_6 = Portal.Create(PortalType.Locked).From(map_2_5, 12, 23).To(map_2_6, 12, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_3_5_to_3_4 = Portal.Create(PortalType.TsNormal).From(map_3_5, 12, 1).To(map_3_4, 12, 23).MinimapOrientation(PortalMinimapOrientation.North)
local portal_3_5_to_4_5 = Portal.Create(PortalType.TsNormal).From(map_3_5, 23, 12).To(map_4_5, 1, 12).MinimapOrientation(PortalMinimapOrientation.East)
local portal_3_5_to_2_5 = Portal.Create(PortalType.TsNormal).From(map_3_5, 1, 12).To(map_2_5, 23, 12).MinimapOrientation(PortalMinimapOrientation.West)
local portal_4_5_to_4_6 = Portal.Create(PortalType.Locked).From(map_4_5, 12, 23).To(map_4_6, 12, 1).MinimapOrientation(PortalMinimapOrientation.South)
local portal_4_5_to_3_5 = Portal.Create(PortalType.Locked).From(map_4_5, 1, 12).To(map_3_5, 23, 12).MinimapOrientation(PortalMinimapOrientation.West)
local portal_3_4_to_UNKNOWN = Portal.Create(PortalType.TSEnd).From(map_3_4, 12, 1).To(map_3_4, 12, 1).MinimapOrientation(PortalMinimapOrientation.North)
local portal_3_4_to_3_5 = Portal.Create(PortalType.TsNormal).From(map_3_4, 12, 23).To(map_3_5, 12, 1).MinimapOrientation(PortalMinimapOrientation.South)

map_6_6.AddPortal(portal_6_6_to_5_6)
map_5_6.AddPortal(portal_5_6_to_6_6)
map_5_6.AddPortal(portal_5_6_to_4_6)
map_4_6.AddPortal(portal_4_6_to_4_5)
map_4_6.AddPortal(portal_4_6_to_5_6)
map_4_6.AddPortal(portal_4_6_to_4_7)
map_4_7.AddPortal(portal_4_7_to_4_6)
map_4_7.AddPortal(portal_4_7_to_3_7)
map_3_7.AddPortal(portal_3_7_to_4_7)
map_3_7.AddPortal(portal_3_7_to_3_8)
map_3_7.AddPortal(portal_3_7_to_2_7)
map_3_8.AddPortal(portal_3_8_to_3_7)
map_3_8.AddPortal(portal_3_8_to_UNKNOWN)
map_2_7.AddPortal(portal_2_7_to_2_6)
map_2_7.AddPortal(portal_2_7_to_3_7)
map_2_6.AddPortal(portal_2_6_to_2_5)
map_2_6.AddPortal(portal_2_6_to_2_7)
map_2_6.AddPortal(portal_2_6_to_1_6)
map_1_6.AddPortal(portal_1_6_to_2_6)
map_1_6.AddPortal(portal_1_6_to_UNKNOWN)
map_2_5.AddPortal(portal_2_5_to_3_5)
map_2_5.AddPortal(portal_2_5_to_2_6)
map_3_5.AddPortal(portal_3_5_to_3_4)
map_3_5.AddPortal(portal_3_5_to_4_5)
map_3_5.AddPortal(portal_3_5_to_2_5)
map_4_5.AddPortal(portal_4_5_to_4_6)
map_4_5.AddPortal(portal_4_5_to_3_5)
map_3_4.AddPortal(portal_3_4_to_UNKNOWN)
map_3_4.AddPortal(portal_3_4_to_3_5)

--- Map 6_6
map_6_6.OnMapJoin({
    Event.TryStartTaskForMap(map_6_6),
})
---

--- Map 5_6
map_5_6.OnMapJoin({
    Event.TryStartTaskForMap(map_5_6),
})
---

--- Map 4_6
map_4_6.OnMapJoin({
    Event.TryStartTaskForMap(map_4_6),
})
---

--- Map 4_5
map_4_5.AddMonsters({
    Monster.CreateWithVnum(150).At(6, 15).Facing(3), -- Elite Kenko Spearman [16:56:27]
    Monster.CreateWithVnum(147).At(3, 9).Facing(6), -- Elite Kenko Swordsman [16:56:27]
    Monster.CreateWithVnum(147).At(5, 11).Facing(2).SpawnAfterMobsKilled(1), -- Elite Kenko Swordsman [16:56:29]
    Monster.CreateWithVnum(147).At(11, 19).Facing(6).SpawnAfterMobsKilled(1), -- Elite Kenko Swordsman [16:56:29]
    Monster.CreateWithVnum(147).At(9, 18).Facing(5).SpawnAfterMobsKilled(2), -- Elite Kenko Swordsman [16:56:31]
})
map_4_5.OnMapJoin({
    Event.TryStartTaskForMap(map_4_5),
})
map_4_5.OnTaskFinish({
    Event.OpenPortal(portal_4_5_to_3_5),
    Event.OpenPortal(portal_4_5_to_4_6),
})
---

--- Map 3_5
map_3_5.OnMapJoin({
    Event.TryStartTaskForMap(map_3_5),
})
---

--- Map 2_5
map_2_5.AddMonsterWaves({
    -- wave 1
    MonsterWave.CreateWithDelay(0 * 30).WithMonsters({
        Monster.CreateWithVnum(147).At(19, 14).Facing(0), -- Elite Kenko Swordsman [16:54:02]
        Monster.CreateWithVnum(147).At(9, 18).Facing(6), -- Elite Kenko Swordsman [16:54:02]
        Monster.CreateWithVnum(149).At(17, 5).Facing(4), -- Kenko Spearman [16:54:02]
    }),
    -- wave 2
    MonsterWave.CreateWithDelay(1 * 30).WithMonsters({
        Monster.CreateWithVnum(147).At(19, 5).Facing(5), -- Elite Kenko Swordsman [16:54:32]
        Monster.CreateWithVnum(147).At(10, 15).Facing(5), -- Elite Kenko Swordsman [16:54:32]
        Monster.CreateWithVnum(149).At(12, 18).Facing(7), -- Kenko Spearman [16:54:32]
    }),
    -- wave 3
    MonsterWave.CreateWithDelay(2 * 30).WithMonsters({
        Monster.CreateWithVnum(147).At(15, 20).Facing(7), -- Elite Kenko Swordsman [16:55:02]
        Monster.CreateWithVnum(147).At(5, 15).Facing(3), -- Elite Kenko Swordsman [16:55:02]
        Monster.CreateWithVnum(149).At(15, 17).Facing(5), -- Kenko Spearman [16:55:02]
    }),
    -- wave 4
    MonsterWave.CreateWithDelay(3 * 30).WithMonsters({
        Monster.CreateWithVnum(147).At(6, 13).Facing(2), -- Elite Kenko Swordsman [16:55:32]
        Monster.CreateWithVnum(147).At(5, 17).Facing(1), -- Elite Kenko Swordsman [16:55:32]
        Monster.CreateWithVnum(149).At(16, 14).Facing(4), -- Kenko Spearman [16:55:32]
    }),
    -- wave 5
    MonsterWave.CreateWithDelay(4 * 30).WithMonsters({
        Monster.CreateWithVnum(147).At(9, 9).Facing(2), -- Elite Kenko Swordsman [16:56:02]
        Monster.CreateWithVnum(147).At(18, 5).Facing(2), -- Elite Kenko Swordsman [16:56:02]
        Monster.CreateWithVnum(149).At(13, 12).Facing(2), -- Kenko Spearman [16:56:02]
        Monster.CreateWithVnum(153).At(20, 19).Facing(6), -- Elite Kenko Raider [16:56:02]
        Monster.CreateWithVnum(153).At(14, 10).Facing(1), -- Elite Kenko Raider [16:56:02]
        Monster.CreateWithVnum(153).At(7, 14).Facing(7), -- Elite Kenko Raider [16:56:02]
        Monster.CreateWithVnum(153).At(13, 8).Facing(4), -- Elite Kenko Raider [16:56:02]
    }),
})
map_2_5.OnMapJoin({
    Event.TryStartTaskForMap(map_2_5),
})
map_2_5.OnTaskFinish({
    Event.OpenPortal(portal_2_5_to_2_6),
    Event.OpenPortal(portal_2_5_to_3_5),
    Event.DespawnAllMobsInRoom(map_2_5),
})
---

--- Map 4_7
map_4_7.AddMonsters({
    Monster.CreateWithVnum(147).At(16, 12).Facing(6), -- Elite Kenko Swordsman [16:52:10]
    Monster.CreateWithVnum(147).At(12, 9).Facing(4), -- Elite Kenko Swordsman [16:52:10]
    Monster.CreateWithVnum(147).At(9, 7).Facing(2), -- Elite Kenko Swordsman [16:52:10]
    Monster.CreateWithVnum(153).At(7, 12).Facing(6).SpawnAfterMobsKilled(3), -- Elite Kenko Raider [16:52:15]
    Monster.CreateWithVnum(150).At(14, 15).Facing(3).SpawnAfterMobsKilled(3), -- Elite Kenko Spearman [16:52:15]
    Monster.CreateWithVnum(150).At(6, 10).Facing(6).SpawnAfterMobsKilled(5), -- Elite Kenko Spearman [16:52:18]
    Monster.CreateWithVnum(153).At(11, 15).Facing(6).SpawnAfterMobsKilled(5), -- Elite Kenko Raider [16:52:18]
})
map_4_7.OnMapJoin({
    Event.TryStartTaskForMap(map_4_7),
})
map_4_7.OnTaskFinish({
    Event.OpenPortal(portal_4_7_to_4_6),
    Event.OpenPortal(portal_4_7_to_3_7),
})
---

--- Map 3_7
map_3_7.OnMapJoin({
    Event.TryStartTaskForMap(map_3_7),
})
---

--- Map 2_7
map_2_7.AddMonsters({
    Monster.CreateWithVnum(153).At(21, 16).Facing(6), -- Elite Kenko Raider [16:52:58]
    Monster.CreateWithVnum(153).At(17, 17).Facing(4), -- Elite Kenko Raider [16:52:58]
    Monster.CreateWithVnum(153).At(7, 8).Facing(1), -- Elite Kenko Raider [16:52:58]
    Monster.CreateWithVnum(153).At(7, 5).Facing(2), -- Elite Kenko Raider [16:52:58]
    Monster.CreateWithVnum(149).At(15, 5).Facing(6).SpawnAfterMobsKilled(1), -- Kenko Spearman [16:53:00]
    Monster.CreateWithVnum(149).At(18, 7).Facing(2).SpawnAfterMobsKilled(2), -- Kenko Spearman [16:53:01]
    Monster.CreateWithVnum(149).At(20, 10).Facing(6).SpawnAfterMobsKilled(3), -- Kenko Spearman [16:53:03]
})
map_2_7.AddObjects({
    MapObject.CreateLever().At(11, 16).OnSwitch({
        Event.TogglePortal(portal_2_7_to_2_6),
    }), -- [16:52:58]
    MapObject.CreateLever().At(8, 12).OnSwitch({
        Event.TogglePortal(portal_2_7_to_3_7),
    }), -- [16:52:58]
})
map_2_7.OnMapJoin({
    Event.TryStartTaskForMap(map_2_7),
})
---

--- Map 2_6
map_2_6.OnMapJoin({
    Event.TryStartTaskForMap(map_2_6),
})
---

--- Map 1_6
map_1_6.AddMonsters({
    Monster.CreateWithVnum(147).At(15, 12).Facing(7), -- Elite Kenko Swordsman [16:53:35]
    Monster.CreateWithVnum(147).At(15, 11).Facing(0), -- Elite Kenko Swordsman [16:53:35]
    Monster.CreateWithVnum(147).At(8, 13).Facing(6), -- Elite Kenko Swordsman [16:53:35]
    Monster.CreateWithVnum(147).At(9, 10).Facing(5), -- Elite Kenko Swordsman [16:53:35]
    Monster.CreateWithVnum(150).At(22, 11).Facing(5).SpawnAfterMobsKilled(2), -- Elite Kenko Spearman [16:53:37]
    Monster.CreateWithVnum(153).At(9, 8).Facing(7).SpawnAfterMobsKilled(4), -- Elite Kenko Raider [16:53:40]
    Monster.CreateWithVnum(153).At(10, 16).Facing(1).SpawnAfterMobsKilled(4), -- Elite Kenko Raider [16:53:40]
    Monster.CreateWithVnum(153).At(16, 8).Facing(5).SpawnAfterMobsKilled(4), -- Elite Kenko Raider [16:53:40]
    Monster.CreateWithVnum(153).At(16, 16).Facing(0).SpawnAfterMobsKilled(4), -- Elite Kenko Raider [16:53:40]
    Monster.CreateWithVnum(150).At(5, 11).Facing(5).SpawnAfterMobsKilled(6), -- Elite Kenko Spearman [16:53:42]
})
map_1_6.AddObjects({
    MapObject.CreateBlockButton().At(12, 12).AsObjective(), -- [16:53:35]
})
map_1_6.OnMapJoin({
    Event.TryStartTaskForMap(map_1_6),
})
map_1_6.OnTaskFinish({
    Event.OpenPortal(portal_1_6_to_2_6),
})
---

--- Map 3_4
map_3_4.AddMonsters({
    Monster.CreateWithVnum(147).At(17, 16).Facing(7), -- Elite Kenko Swordsman [16:56:50]
    Monster.CreateWithVnum(150).At(13, 1).Facing(6), -- Elite Kenko Spearman [16:56:50]
    Monster.CreateWithVnum(150).At(11, 1).Facing(4), -- Elite Kenko Spearman [16:56:50]
    Monster.CreateWithVnum(147).At(8, 16).Facing(0), -- Elite Kenko Swordsman [16:56:50]
    Monster.CreateWithVnum(153).At(12, 6).Facing(1).SpawnAfterMobsKilled(2), -- Elite Kenko Raider [16:56:52]
    Monster.CreateWithVnum(153).At(16, 4).Facing(2).SpawnAfterMobsKilled(2), -- Elite Kenko Raider [16:56:52]
    Monster.CreateWithVnum(153).At(8, 4).Facing(2).SpawnAfterMobsKilled(3), -- Elite Kenko Raider [16:56:54]
})
map_3_4.AddObjects({
    MapObject.CreateBlockButton().At(12, 4).AsObjective(), -- [16:56:50]
})
map_3_4.OnMapJoin({
    Event.TryStartTaskForMap(map_3_4),
})
---

--- Map 3_8
map_3_8.AddMonsters({
    Monster.CreateWithVnum(150).At(15, 21).Facing(7), -- Elite Kenko Spearman [16:52:29]
    Monster.CreateWithVnum(153).At(13, 10).Facing(7), -- Elite Kenko Raider [16:52:29]
    Monster.CreateWithVnum(150).At(11, 22).Facing(3), -- Elite Kenko Spearman [16:52:29]
    Monster.CreateWithVnum(147).At(6, 8).Facing(6).SpawnAfterMobsKilled(2), -- Elite Kenko Swordsman [16:52:32]
    Monster.CreateWithVnum(147).At(6, 11).Facing(4).SpawnAfterMobsKilled(2), -- Elite Kenko Swordsman [16:52:32]
    Monster.CreateWithVnum(147).At(6, 14).Facing(7).SpawnAfterMobsKilled(2), -- Elite Kenko Swordsman [16:52:32]
    Monster.CreateWithVnum(147).At(18, 8).Facing(3).SpawnAfterMobsKilled(5), -- Elite Kenko Swordsman [16:52:36]
    Monster.CreateWithVnum(147).At(18, 13).Facing(0).SpawnAfterMobsKilled(5), -- Elite Kenko Swordsman [16:52:36]
    Monster.CreateWithVnum(147).At(19, 11).Facing(6).SpawnAfterMobsKilled(5), -- Elite Kenko Swordsman [16:52:36]
})
map_3_8.AddObjects({
    MapObject.CreateBlockButton().At(12, 19).AsObjective(), -- [16:52:29]
})
map_3_8.OnMapJoin({
    Event.TryStartTaskForMap(map_3_8),
})
---

local ts = TimeSpace.Create(631)  -- TimeSpace ID
    .SetMaps({map_6_6, map_5_6, map_4_6, map_4_5, map_3_5, map_2_5, map_4_7, map_3_7, map_2_7, map_2_6, map_1_6, map_3_4, map_3_8})
    .SetSpawn(Location.InMap(map_6_6).At(6, 12))
    .SetLives(2)
    .SetObjectives(objectives)
    .SetDurationInSeconds(600)
    .SetBonusPointItemDropChance(5000)
return ts
