local MapFlags = {}

MapFlags.ACT_1 = 0
MapFlags.ACT_2 = 1
MapFlags.ACT_3 = 2
MapFlags.ACT_4 = 3
MapFlags.ACT_5_1 = 4
MapFlags.ACT_5_2 = 5
MapFlags.ACT_6_1 = 6
MapFlags.ACT_6_2 = 7
MapFlags.ACT_7 = 8

-- FACTION
MapFlags.ANGEL_SIDE = 30
MapFlags.DEMON_SIDE = 31

MapFlags.NOSVILLE = 40
MapFlags.PORT_ALVEUS = 41

-- TYPES
MapFlags.IS_BASE_MAP = 50
MapFlags.IS_MINILAND_MAP = 51

-- FLAGS
MapFlags.HAS_PVP_ENABLED = 100
MapFlags.HAS_PVP_FACTION_ENABLED = 101
MapFlags.HAS_PVP_FAMILY_ENABLED = 102
MapFlags.HAS_USER_SHOPS_DISABLED = 103
MapFlags.HAS_DROP_DIRECTLY_IN_INVENTORY_ENABLED = 104
MapFlags.HAS_CHAMPION_EXPERIENCE_ENABLED = 106
MapFlags.HAS_SEALED_VESSELS_DISABLED = 107
MapFlags.HAS_RAID_TEAM_SUMMON_STONE_ENABLED = 108
MapFlags.HAS_SIGNPOSTS_ENABLED = 110

-- DEBUFFS
MapFlags.HAS_IMMUNITY_ON_MAP_CHANGE_ENABLED = 200
MapFlags.HAS_BURNING_SWORD_ENABLED = 201

return MapFlags