-- Raid Script generated by friends111's python script. Replace all %TODO% values accordingly, check for errors (packet-generation isn't perfect), and modify things if needed.
local Map = require('Map')
local Monster = require ('Monster')
local Event = require('Event')
local MapObject = require('MapObject')
local Portal = require('Portal')
local Raid = require('Raid')
local RaidType = require('RaidType')
local RaidFinishType = require('RaidFinishType')
local Location = require('Location')
local RaidRequirement = require('RaidRequirement')
local RaidDrop = require('RaidDrop')
local Drop = require('Drop')
local RaidReward = require('RaidReward')
local RaidBox = require('RaidBox')
local RaidBoxRarity = require('RaidBoxRarity')
local MonsterWave = require('MonsterWave')

local requirement = RaidRequirement.Create()
    .WithMinimumLevel(30)
    .WithMaximumLevel(99) -- 49
    .WithMinimumHeroLevel(0)
    .WithMaximumHeroLevel(70)
    .WithMinimumParticipant(1) -- 5
    .WithMaximumParticipant(15)

local raidBox = RaidBox.Create()
    .WithVnum(1234) -- Your Raidbox vnum
    .WithBoxRarity(RaidBoxRarity.CreateBoxRarity().WithRarity(1).WithChance(1500))
    .WithBoxRarity(RaidBoxRarity.CreateBoxRarity().WithRarity(2).WithChance(2000))
    .WithBoxRarity(RaidBoxRarity.CreateBoxRarity().WithRarity(3).WithChance(3000))
    .WithBoxRarity(RaidBoxRarity.CreateBoxRarity().WithRarity(4).WithChance(2100))
    .WithBoxRarity(RaidBoxRarity.CreateBoxRarity().WithRarity(5).WithChance(1000))
    .WithBoxRarity(RaidBoxRarity.CreateBoxRarity().WithRarity(6).WithChance(300))
    .WithBoxRarity(RaidBoxRarity.CreateBoxRarity().WithRarity(7).WithChance(100))

local reward = RaidReward.Create()
    .WithRaidBox(raidBox)
    .WithDefaultReputation()

local map_0_1 = Map.Create().WithMapId(2511)
local map_0_0 = Map.Create().WithMapId(2512) -- Boss room

local portal_0 = Portal.CreateLocked().From(map_0_1, 154, 11).To(map_0_0, 26, 40)
local portal_1 = Portal.CreateLocked().From(map_0_0, 26, 40).To(map_0_0, 26, 40)

map_0_1.AddPortal(portal_0)
map_0_0.AddPortal(portal_1)

map_0_1.AddMonsters({
    -- Objective mobs --
    Monster.CreateWithVnum(283).At(82, 118).AsObjective(), -- Cuby
    Monster.CreateWithVnum(283).At(52, 16).AsObjective(), -- Cuby
    Monster.CreateWithVnum(283).At(32, 95).AsObjective().OnHalfHp({
        Event.MonsterSummon({
            Monster.CreateWithVnum(40).At(51, 99), -- Wild Pii
            Monster.CreateWithVnum(40).At(44, 99), -- Wild Pii
            Monster.CreateWithVnum(40).At(42, 96), -- Wild Pii
            Monster.CreateWithVnum(40).At(42, 96), -- Wild Pii
            Monster.CreateWithVnum(40).At(45, 99), -- Wild Pii
            Monster.CreateWithVnum(40).At(42, 96), -- Wild Pii
            Monster.CreateWithVnum(40).At(42, 96), -- Wild Pii
            Monster.CreateWithVnum(40).At(42, 96), -- Wild Pii
            Monster.CreateWithVnum(40).At(42, 96), -- Wild Pii
            Monster.CreateWithVnum(40).At(42, 96), -- Wild Pii
            Monster.CreateWithVnum(40).At(42, 96), -- Wild Pii
            Monster.CreateWithVnum(40).At(42, 96), -- Wild Pii
            Monster.CreateWithVnum(40).At(42, 96), -- Wild Pii
        }),
    }), -- Cuby
    Monster.CreateWithVnum(283).At(26, 33).AsObjective(), -- Cuby
    Monster.CreateWithVnum(283).At(20, 154).AsObjective().OnHalfHp({
        Event.MonsterSummon({
            Monster.CreateWithVnum(280).At(60, 66), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(57, 62), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(57, 62), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(57, 62), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(57, 63), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(57, 63), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(57, 62), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(59, 63), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(57, 62), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(57, 62), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(48, 57), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(49, 49), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(42, 54), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(49, 53), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(49, 49), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(45, 52), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(49, 50), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(49, 49), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(44, 59), -- Small Red Jelly
            Monster.CreateWithVnum(280).At(43, 49), -- Small Red Jelly
        }),
    }), -- Cuby
    Monster.CreateWithVnum(283).At(158, 48).AsObjective(), -- Cuby
    Monster.CreateWithVnum(283).At(153, 19).AsObjective(), -- Cuby
    Monster.CreateWithVnum(283).At(142, 84).AsObjective(), -- Cuby
    Monster.CreateWithVnum(283).At(137, 59).AsObjective(), -- Cuby
    Monster.CreateWithVnum(283).At(136, 153).AsObjective(), -- Cuby
    Monster.CreateWithVnum(283).At(108, 6).AsObjective().OnHalfHp({
        Event.MonsterSummon({
            Monster.CreateWithVnum(45).At(117, 13), -- Soft Pii Pod
            Monster.CreateWithVnum(45).At(122, 12), -- Soft Pii Pod
            Monster.CreateWithVnum(45).At(118, 13), -- Soft Pii Pod
            Monster.CreateWithVnum(45).At(115, 9), -- Soft Pii Pod
            Monster.CreateWithVnum(45).At(119, 15), -- Soft Pii Pod
            Monster.CreateWithVnum(45).At(115, 9), -- Soft Pii Pod
            Monster.CreateWithVnum(45).At(122, 11), -- Soft Pii Pod
            Monster.CreateWithVnum(45).At(115, 9), -- Soft Pii Pod
            Monster.CreateWithVnum(45).At(119, 10), -- Soft Pii Pod
            Monster.CreateWithVnum(45).At(115, 17), -- Soft Pii Pod
            Monster.CreateWithVnum(36).At(118, 13), -- Soft Pii
            Monster.CreateWithVnum(36).At(117, 12), -- Soft Pii
        }),
    }), -- Cuby
    -- Normal mobs --
    Monster.CreateWithVnum(82).At(16, 45), -- Pink Jelly
    Monster.CreateWithVnum(82).At(16, 35), -- Pink Jelly
    Monster.CreateWithVnum(82).At(15, 32), -- Pink Jelly
    Monster.CreateWithVnum(82).At(14, 38), -- Pink Jelly
    Monster.CreateWithVnum(82).At(14, 24), -- Pink Jelly
    Monster.CreateWithVnum(82).At(13, 47), -- Pink Jelly
    Monster.CreateWithVnum(82).At(13, 42), -- Pink Jelly
    Monster.CreateWithVnum(82).At(12, 32), -- Pink Jelly
    Monster.CreateWithVnum(82).At(11, 35), -- Pink Jelly
    Monster.CreateWithVnum(82).At(11, 27), -- Pink Jelly
    Monster.CreateWithVnum(82).At(10, 45), -- Pink Jelly
    Monster.CreateWithVnum(48).At(64, 99), -- Baby Wild Pii Pod
    Monster.CreateWithVnum(48).At(61, 91), -- Baby Wild Pii Pod
    Monster.CreateWithVnum(48).At(58, 100), -- Baby Wild Pii Pod
    Monster.CreateWithVnum(48).At(57, 91), -- Baby Wild Pii Pod
    Monster.CreateWithVnum(48).At(52, 99), -- Baby Wild Pii Pod
    Monster.CreateWithVnum(48).At(52, 91), -- Baby Wild Pii Pod
    Monster.CreateWithVnum(48).At(46, 91), -- Baby Wild Pii Pod
    Monster.CreateWithVnum(48).At(45, 98), -- Baby Wild Pii Pod
    Monster.CreateWithVnum(48).At(41, 91), -- Baby Wild Pii Pod
    Monster.CreateWithVnum(48).At(39, 98), -- Baby Wild Pii Pod
    Monster.CreateWithVnum(48).At(34, 99), -- Baby Wild Pii Pod
    Monster.CreateWithVnum(48).At(32, 91), -- Baby Wild Pii Pod
    Monster.CreateWithVnum(4).At(147, 82), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(147, 80), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(146, 88), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(146, 84), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(143, 88), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(143, 79), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(141, 90), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(139, 87), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(139, 78), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(138, 83), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(138, 80), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(135, 83), -- Dusi-Fox
    Monster.CreateWithVnum(340).At(142, 118), -- Angry Chicken
    Monster.CreateWithVnum(340).At(141, 118), -- Angry Chicken
    Monster.CreateWithVnum(340).At(140, 118), -- Angry Chicken
    Monster.CreateWithVnum(340).At(139, 118), -- Angry Chicken
    Monster.CreateWithVnum(340).At(138, 118), -- Angry Chicken
    Monster.CreateWithVnum(340).At(137, 118), -- Angry Chicken
    Monster.CreateWithVnum(340).At(135, 118), -- Angry Chicken
    Monster.CreateWithVnum(340).At(134, 118), -- Angry Chicken
    Monster.CreateWithVnum(340).At(133, 118), -- Angry Chicken
    Monster.CreateWithVnum(340).At(132, 118), -- Angry Chicken
    Monster.CreateWithVnum(340).At(130, 118), -- Angry Chicken
    Monster.CreateWithVnum(271).At(57, 37), -- Dark Gargs
    Monster.CreateWithVnum(271).At(41, 37), -- Dark Gargs
    Monster.CreateWithVnum(208).At(156, 20), -- Angry Beehive
    Monster.CreateWithVnum(208).At(155, 18), -- Angry Beehive
    Monster.CreateWithVnum(208).At(154, 21), -- Angry Beehive
    Monster.CreateWithVnum(208).At(153, 17), -- Angry Beehive
    Monster.CreateWithVnum(208).At(152, 21), -- Angry Beehive
    Monster.CreateWithVnum(208).At(151, 17), -- Angry Beehive
    Monster.CreateWithVnum(208).At(150, 19), -- Angry Beehive
    Monster.CreateWithVnum(208).At(129, 28), -- Angry Beehive
    Monster.CreateWithVnum(208).At(107, 26), -- Angry Beehive
    Monster.CreateWithVnum(17).At(26, 130), -- Nervous Ram
    Monster.CreateWithVnum(17).At(25, 117), -- Nervous Ram
    Monster.CreateWithVnum(17).At(22, 135), -- Nervous Ram
    Monster.CreateWithVnum(17).At(21, 123), -- Nervous Ram
    Monster.CreateWithVnum(17).At(21, 108), -- Nervous Ram
    Monster.CreateWithVnum(14).At(108, 81), -- Big Mufflon
    Monster.CreateWithVnum(14).At(106, 87), -- Big Mufflon
    Monster.CreateWithVnum(14).At(105, 92), -- Big Mufflon
    Monster.CreateWithVnum(14).At(104, 96), -- Big Mufflon
    Monster.CreateWithVnum(14).At(104, 82), -- Big Mufflon
    Monster.CreateWithVnum(14).At(102, 92), -- Big Mufflon
    Monster.CreateWithVnum(14).At(101, 89), -- Big Mufflon
    Monster.CreateWithVnum(11).At(26, 135), -- Angry Wooly
    Monster.CreateWithVnum(11).At(24, 124), -- Angry Wooly
    Monster.CreateWithVnum(11).At(24, 111), -- Angry Wooly
    Monster.CreateWithVnum(11).At(23, 130), -- Angry Wooly
    Monster.CreateWithVnum(11).At(21, 117), -- Angry Wooly
    Monster.CreateWithVnum(11).At(21, 104), -- Angry Wooly
    Monster.CreateWithVnum(104).At(28, 71), -- Large Steel Hamster
    Monster.CreateWithVnum(104).At(27, 73), -- Large Steel Hamster
    Monster.CreateWithVnum(104).At(26, 72), -- Large Steel Hamster
    Monster.CreateWithVnum(104).At(24, 154), -- Large Steel Hamster
    Monster.CreateWithVnum(103).At(76, 18), -- Steel Hamster
    Monster.CreateWithVnum(103).At(75, 14), -- Steel Hamster
    Monster.CreateWithVnum(103).At(67, 23), -- Steel Hamster
    Monster.CreateWithVnum(103).At(57, 11), -- Steel Hamster
    Monster.CreateWithVnum(100).At(133, 159), -- Poisonous Hamster
    Monster.CreateWithVnum(100).At(122, 159), -- Poisonous Hamster
    Monster.CreateWithVnum(100).At(116, 156), -- Poisonous Hamster
    Monster.CreateWithVnum(100).At(113, 150), -- Poisonous Hamster
    Monster.CreateWithVnum(100).At(112, 146), -- Poisonous Hamster
    Monster.CreateWithVnum(100).At(110, 157), -- Poisonous Hamster
    Monster.CreateWithVnum(100).At(110, 153), -- Poisonous Hamster
    Monster.CreateWithVnum(100).At(109, 78), -- Poisonous Hamster
    Monster.CreateWithVnum(100).At(108, 149), -- Poisonous Hamster
    Monster.CreateWithVnum(100).At(107, 84), -- Poisonous Hamster
    Monster.CreateWithVnum(100).At(107, 75), -- Poisonous Hamster
    Monster.CreateWithVnum(100).At(105, 77), -- Poisonous Hamster
    Monster.CreateWithVnum(100).At(103, 73), -- Poisonous Hamster
    Monster.CreateWithVnum(100).At(102, 86), -- Poisonous Hamster
    Monster.CreateWithVnum(14).At(70, 15), -- Big Mufflon
    Monster.CreateWithVnum(14).At(66, 18), -- Big Mufflon
    Monster.CreateWithVnum(14).At(45, 15), -- Big Mufflon
    Monster.CreateWithVnum(14).At(37, 22), -- Big Mufflon
    Monster.CreateWithVnum(14).At(36, 18), -- Big Mufflon
    Monster.CreateWithVnum(14).At(32, 14), -- Big Mufflon
    Monster.CreateWithVnum(13).At(161, 155), -- Mufflon
    Monster.CreateWithVnum(13).At(161, 150), -- Mufflon
    Monster.CreateWithVnum(13).At(160, 159), -- Mufflon
    Monster.CreateWithVnum(13).At(160, 148), -- Mufflon
    Monster.CreateWithVnum(13).At(153, 160), -- Mufflon
    Monster.CreateWithVnum(13).At(153, 156), -- Mufflon
    Monster.CreateWithVnum(13).At(153, 150), -- Mufflon
    Monster.CreateWithVnum(7).At(83, 12), -- Oto-Fox
    Monster.CreateWithVnum(7).At(81, 16), -- Oto-Fox
    Monster.CreateWithVnum(7).At(79, 21), -- Oto-Fox
    Monster.CreateWithVnum(7).At(57, 19), -- Oto-Fox
    Monster.CreateWithVnum(7).At(57, 14), -- Oto-Fox
    Monster.CreateWithVnum(7).At(54, 55), -- Oto-Fox
    Monster.CreateWithVnum(7).At(54, 53), -- Oto-Fox
    Monster.CreateWithVnum(7).At(54, 51), -- Oto-Fox
    Monster.CreateWithVnum(7).At(54, 49), -- Oto-Fox
    Monster.CreateWithVnum(7).At(45, 19), -- Oto-Fox
    Monster.CreateWithVnum(7).At(41, 14), -- Oto-Fox
    Monster.CreateWithVnum(7).At(157, 59), -- Oto-Fox
    Monster.CreateWithVnum(7).At(155, 52), -- Oto-Fox
    Monster.CreateWithVnum(7).At(155, 47), -- Oto-Fox
    Monster.CreateWithVnum(4).At(38, 166), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(37, 156), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(36, 160), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(34, 163), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(32, 166), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(27, 167), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(21, 166), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(20, 162), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(15, 166), -- Dusi-Fox
    Monster.CreateWithVnum(4).At(14, 161), -- Dusi-Fox
})

map_0_1.AddObjects({
    MapObject.CreateTeleportLever().At(86, 15).OnSwitch({
        Event.Teleport(map_0_1, 86, 15, 158, 154, 4),
    }),
    MapObject.CreateTeleportLever().At(109, 139).OnSwitch({
        Event.Teleport(map_0_1, 109, 139, 86, 15, 4),
    }),
    MapObject.CreateTrigger().At(79, 107).AsRaidObjective().OnTrigger({
        Event.MonsterSummon({
            Monster.CreateWithVnum(37).At(80, 106), -- Pii
            Monster.CreateWithVnum(37).At(80, 108), -- Pii
            Monster.CreateWithVnum(37).At(79, 105), -- Pii
            Monster.CreateWithVnum(37).At(77, 105), -- Pii
            Monster.CreateWithVnum(37).At(79, 107), -- Pii
            Monster.CreateWithVnum(37).At(78, 105), -- Pii
            Monster.CreateWithVnum(37).At(78, 108), -- Pii
            Monster.CreateWithVnum(37).At(77, 105), -- Pii
            Monster.CreateWithVnum(37).At(79, 109), -- Pii
            Monster.CreateWithVnum(37).At(77, 105), -- Pii
            Monster.CreateWithVnum(37).At(79, 107), -- Pii
            Monster.CreateWithVnum(37).At(80, 108), -- Pii
            Monster.CreateWithVnum(37).At(80, 106), -- Pii
            Monster.CreateWithVnum(37).At(80, 109), -- Pii
            Monster.CreateWithVnum(37).At(77, 108), -- Pii
            Monster.CreateWithVnum(37).At(80, 108), -- Pii
            Monster.CreateWithVnum(37).At(77, 108), -- Pii
            Monster.CreateWithVnum(37).At(81, 108), -- Pii
            Monster.CreateWithVnum(37).At(81, 106), -- Pii
            Monster.CreateWithVnum(37).At(81, 105), -- Pii
            Monster.CreateWithVnum(37).At(80, 107), -- Pii
            Monster.CreateWithVnum(37).At(78, 109), -- Pii
            Monster.CreateWithVnum(37).At(80, 105), -- Pii
            Monster.CreateWithVnum(37).At(81, 106), -- Pii
            Monster.CreateWithVnum(37).At(79, 105), -- Pii
            Monster.CreateWithVnum(37).At(77, 108), -- Pii
            Monster.CreateWithVnum(37).At(77, 106), -- Pii
            Monster.CreateWithVnum(37).At(80, 106), -- Pii
            Monster.CreateWithVnum(37).At(77, 106), -- Pii
            Monster.CreateWithVnum(37).At(80, 106), -- Pii
        }),
    }),
    MapObject.CreateTrigger().At(41, 70).AsRaidObjective(),
    MapObject.CreateTrigger().At(26, 162).AsRaidObjective().OnTrigger({
        Event.MonsterSummon({
            Monster.CreateWithVnum(100).At(63, 96), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(50, 93), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(39, 93), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(47, 93), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(35, 96), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(58, 98), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(39, 96), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(44, 96), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(38, 96), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(54, 97), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(62, 93), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(57, 97), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(37, 97), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(42, 93), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(59, 97), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(59, 98), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(61, 94), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(51, 95), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(65, 94), -- Poisonous Hamster
            Monster.CreateWithVnum(100).At(64, 98), -- Poisonous Hamster
        }),
    }),
})

map_0_1.OnObjectivesCompleted({
    Event.OpenPortal(portal_0),
})

map_0_0.AddMonsters({
    -- Objective mobs --
    -- Boss monster is added below separately
    -- Normal mobs --
    Monster.CreateWithVnum(167).At(7, 8), -- Weak Red Jelly
})

local boss = Monster.CreateWithVnum(282).At(26, 28).AsBoss() -- Mother Cuby

local drops = RaidDrop.Create(boss)
    .WithGoldRange(5000, 10000)
    .WithGoldStackCount(30)
    .WithDrops({
        Drop.Create(1011, 2), -- Huge Recovery Potion
        Drop.Create(1011, 2), -- Huge Recovery Potion
        Drop.Create(1011, 2), -- Huge Recovery Potion
        Drop.Create(1011, 2), -- Huge Recovery Potion
        Drop.Create(1011, 2), -- Huge Recovery Potion
        Drop.Create(1013, 1), -- Gillion Stone
        Drop.Create(1015, 2), -- Soul Gem
        Drop.Create(1016, 2), -- Complete Soul Gem
        Drop.Create(1018, 3), -- Cellon (Level 2)
        Drop.Create(1018, 3), -- Cellon (Level 2)
        Drop.Create(1018, 3), -- Cellon (Level 2)
        Drop.Create(1018, 3), -- Cellon (Level 2)
        Drop.Create(1019, 4), -- Cellon (Level 3)
        Drop.Create(1019, 4), -- Cellon (Level 3)
        Drop.Create(1019, 4), -- Cellon (Level 3)
        Drop.Create(1019, 4), -- Cellon (Level 3)
        Drop.Create(1029, 1), -- Half Moon Crystal
        Drop.Create(1030, 1), -- Full Moon Crystal
        Drop.Create(2035, 2), -- Normal Metal
        Drop.Create(2039, 2), -- Normal Wood
        Drop.Create(2043, 2), -- Normal Rag
        Drop.Create(2047, 2), -- Normal Leather
        Drop.Create(2135, 2), -- Cheese Sticks
        Drop.Create(2135, 2), -- Cheese Sticks
        Drop.Create(2136, 2), -- French Fries
        Drop.Create(2136, 2), -- French Fries
        Drop.Create(2170, 1), -- Team Stone
    })
    .WithDropsStackCount(15)

map_0_0.AddMonsterWaves({
    MonsterWave.CreateWithDelay(30).AsLoop(20).WithMonsters({
        Monster.CreateWithVnum(167).At(11, 12).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Red Jelly
        Monster.CreateWithVnum(167).At(11, 9).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Red Jelly
        Monster.CreateWithVnum(167).At(4, 10).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Red Jelly
        Monster.CreateWithVnum(167).At(6, 12).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Red Jelly
        Monster.CreateWithVnum(167).At(6, 9).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Red Jelly
        Monster.CreateWithVnum(167).At(7, 8).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Red Jelly
        Monster.CreateWithVnum(167).At(8, 10).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Red Jelly
        Monster.CreateWithVnum(167).At(9, 6).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Red Jelly
        Monster.CreateWithVnum(168).At(4, 47).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Invisible Jelly
        Monster.CreateWithVnum(168).At(4, 47).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Invisible Jelly
        Monster.CreateWithVnum(168).At(4, 47).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Invisible Jelly
        Monster.CreateWithVnum(168).At(6, 49).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Invisible Jelly
        Monster.CreateWithVnum(168).At(8, 45).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Invisible Jelly
        Monster.CreateWithVnum(168).At(8, 45).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Invisible Jelly
        Monster.CreateWithVnum(168).At(8, 50).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Invisible Jelly
        Monster.CreateWithVnum(168).At(10, 47).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Invisible Jelly
        Monster.CreateWithVnum(168).At(11, 51).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Invisible Jelly
        Monster.CreateWithVnum(168).At(12, 49).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Invisible Jelly
        Monster.CreateWithVnum(169).At(42, 49).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Pink Jelly
        Monster.CreateWithVnum(169).At(43, 51).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Pink Jelly
        Monster.CreateWithVnum(169).At(44, 44).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Pink Jelly
        Monster.CreateWithVnum(169).At(45, 48).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Pink Jelly
        Monster.CreateWithVnum(169).At(47, 46).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Pink Jelly
        Monster.CreateWithVnum(169).At(49, 44).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Pink Jelly
        Monster.CreateWithVnum(169).At(49, 47).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Pink Jelly
        Monster.CreateWithVnum(170).At(41, 8).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Dark Jelly
        Monster.CreateWithVnum(170).At(42, 4).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Dark Jelly
        Monster.CreateWithVnum(170).At(43, 7).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Dark Jelly
        Monster.CreateWithVnum(170).At(45, 5).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Dark Jelly
        Monster.CreateWithVnum(170).At(46, 9).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Dark Jelly
        Monster.CreateWithVnum(170).At(46, 12).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Dark Jelly
        Monster.CreateWithVnum(170).At(48, 8).WithMoveToPosition(boss.Position.X, boss.Position.Y), -- Weak Dark Jelly
    }),
})

map_0_0.AddMonster(boss)

map_0_0.OnObjectivesCompleted({
    Event.FinishRaid(RaidFinishType.MissionClear),
})

map_0_0.AfterSlowMotion({
    Event.ThrowRaidDrops(drops),
})

local raid = Raid.Create(RaidType.Cuby) -- Raid ID: 0
    .WithMaps({map_0_1, map_0_0})
    .WithSpawn(Location.InMap(map_0_1).At(77, 167))
    .WithRequirement(requirement)
    .WithReward(reward)
    .WithDuration(40*60)
return raid
